### ISSUE TITLE
Specific Dyn Var inputs don't have proper customized visuals

### ISSUE THREAD

**Issue by ScarsTRF** [Banane9/LogixVisualCustomizer#2]
![20220630000450_1](https://user-images.githubusercontent.com/23484495/176617285-50c82cc7-4044-4e85-b1b3-c984dad80c1e.jpg)

Seems as if some specific Dyn Var inputs such as "SessionAccessLevel" don't have proper visuals for their nodes. I have yet to see any other nodes, but I will post if any others are found.

**Comment by Banane9** [comment]
That enum's part of the CloudX.Shared.dll apparently, which wasn't included in my list yet, will add.

**Comment by Banane9** [comment]
👀 

![Customized Input go brrrr](https://user-images.githubusercontent.com/2124570/176692265-0be8d1fc-4769-4ee6-a3ac-6c6b11b6898f.png)
